# Generated by Django 4.0.2 on 2022-07-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extra',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='oven_baked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[('Small', '25'), ('Medium', '30')], default='Small', max_length=10),
        ),
    ]
