# Generated by Django 4.0.2 on 2022-07-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_order_extra_order_oven_baked_order_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='food_option',
        ),
    ]
