# Generated by Django 4.0.2 on 2022-07-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_order_food_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='food_option',
            field=models.ManyToManyField(null=True, to='mainapp.FoodOptions'),
        ),
    ]
