# Generated by Django 4.0.2 on 2022-07-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_order_food_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='food_option',
            field=models.ManyToManyField(to='mainapp.FoodOptions'),
        ),
    ]
