# Generated by Django 4.0.2 on 2022-07-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_order_food_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='oven_baked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
