# Generated by Django 4.0.2 on 2022-07-03 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_order_oven_baked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='food_option',
        ),
    ]
