# Generated by Django 4.0.2 on 2022-07-03 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_order_food_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='food_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.foodoptions'),
        ),
    ]
