# Generated by Django 4.0.2 on 2022-07-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_remove_order_food_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='food_option',
            field=models.ManyToManyField(to='mainapp.FoodOptions'),
        ),
    ]
